pipeline:
  name: CI - Cypress Testing
  identifier: CI_Cypress_Testing
  projectIdentifier: Femi_Sandbox
  orgIdentifier: sandbox
  tags: {}
  stages:
    - stage:
        name: Cypress Tests
        identifier: Cypress_Tests
        type: CI
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Background
                  name: Start Application
                  identifier: Start_Application
                  spec:
                    shell: Sh
                    command: npm start
              - step:
                  type: Run
                  name: Run Tests
                  identifier: Run_Tests
                  spec:
                    shell: Sh
                    command: |-
                      command: |
                        # Create app directory if it doesn't exist
                        mkdir -p /app
                        
                        # Clone your repository into /app
                        # Replace with your actual repository URL
                        git clone https://github.com/mar4r8k-femi/cypress-course-final.git /app
                        
                        # Navigate to the directory
                        cd /app
                        
                        # Install dependencies
                        npm install
                        
                        # Run Cypress tests
                        npm run cy:run -- --ci-build-id $HARNESS_BUILD_ID
                  strategy:
                    parallelism: 3
          cloneCodebase: true
          caching:
            enabled: true
            paths: []
          buildIntelligence:
            enabled: true
        description: ""
  properties:
    ci:
      codebase:
        connectorRef: femigithub
        repoName: cypress-course-final
        build: <+input>
        sparseCheckout: []
  description: https://engineering.harness.io/using-cypress-parallelization-with-harness-ci-15c149288df4
