pipeline:
  name: CI - Testing
  identifier: CI_Testing
  projectIdentifier: Femi_Sandbox
  orgIdentifier: sandbox
  description: Cypress Testing Example
  tags: {}
  stages:
    - stage:
        name: Cypress Tests
        identifier: Cypress_Tests
        type: CI
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Background
                  name: Start Application
                  identifier: Start_Application
                  spec:
                    shell: Sh
                    command: npm start
              - parallel:
                  - step:
                      type: Run
                      name: Cypress Tests 1
                      identifier: Cypress_Tests_1
                      spec:
                        connectorRef: femidockerhub
                        image: cypress/browsers:node14.16.0-chrome90-ff88
                        shell: Sh
                        command: |-
                          # Clone your repo and navigate to it
                          cd /app
                          npm install
                          npm run cy:run -- --ci-build-id $HARNESS_BUILD_ID
                      envVariables:
                        CYPRESS_RECORD_KEY: <+secrets.getValue("cypress_record_key")>
                        CYPRESS_PARALLEL: "true"
                        HARNESS_BUILD_ID: <+pipeline.sequenceId>
                  - step:
                      type: Run
                      name: Cypress Tests 2
                      identifier: Cypress_Tests_2
                      spec:
                        connectorRef: femidockerhub
                        image: cypress/browsers:node14.16.0-chrome90-ff88
                        shell: Sh
                        command: |-
                          # Clone your repo and navigate to it
                          cd /app
                          npm install
                          npm run cy:run -- --ci-build-id $HARNESS_BUILD_ID
                      envVariables:
                        CYPRESS_RECORD_KEY: <+secrets.getValue("cypress_record_key")>
                        CYPRESS_PARALLEL: "true"
                        HARNESS_BUILD_ID: <+pipeline.sequenceId>
